### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by tamarw** [v3gard/crashplan-log-parser#2]
Hi - python's not my thing and I can't figure out how to use this. Sorry!

I have model.py and logparser.py.

But running them gives this error:
Traceback (most recent call last):
  File "logparser.py", line 10, in <module>
    from crashplan_logparser.model import BackupLogParser
ImportError: No module named crashplan_logparser.model

How do I get said module? I assume it comes out of model.py but running model.py doesn't seem to do anything...

p.s. your email bounces

**Comment by v3gard** [comment]
Hi tamarw.

I just tested cloning the project on a fresh server and it works - so I guess this must be due to a mistake on your end.

After you have cloned the entire project (all the files), you can use the included usage instructions in the project README file. Simply type "python logparser.py".
The error message you sent indicates that you haven't cloned the entire project as it says that some files are missing.

The files in the crashplan_logparser folder are libraries and is not meant to be run directly.
Which e-mail did you try? I just tested the email in the project folder, vegard@haugland.at, and that works fine.

Regards,
v3gard

**Comment by tamarw** [comment]
Hmm, so I suggest a detailed readme because I'm still not having luck here.

I have:
crashplan_logparser 
- in that directory, I have model.py

In the main directory, I have logparser.conf and logparser.py.

I continually get 
.# python logparser.py 
Traceback (most recent call last):
  File "logparser.py", line 10, in <module>
    from crashplan_logparser.model import BackupLogParser
ImportError: No module named crashplan_logparser.model

also, your email...
Delivery to the following recipient failed permanently:

```
 vergard@haugland.at
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain haugland.at by aspmx.l.google.com. [2607:f8b0:4003:c06::1a].

The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/answer/6596 e66si4403344oia.74 - gsmtp

there are no typos or unnecessary spaces!
