### ISSUE TITLE
"list index out of range"?

### ISSUE THREAD

**Issue by JanJoh** [v3gard/crashplan-log-parser#3]
Any pointers?

[root@pentserv01 crashplan_logparser]# crashplanlogparser.py --config=/etc/CrashPlanLogParser.conf list
Command not recognized.
Usage: crashplanlogparser.py [options] COMMAND

[root@pentserv01 crashplan_logparser]# crashplanlogparser.py --config=/etc/CrashPlanLogParser.conf stats
  Scan jobs:    0
Backup jobs:    0
 Total jobs:    0

Traceback (most recent call last):
  File "/usr/local/bin/crashplanlogparser.py", line 83, in <module>
    main()
  File "/usr/local/bin/crashplanlogparser.py", line 72, in main
    blp.get_statistics()
  File "/usr/lib/python2.7/site-packages/crashplan_logparser/model.py", line 148, in get_statistics
    print "Last job completed at %s" % self.jobs[-1].eventStop.time_start
IndexError: list index out of range
[root@pentserv01 crashplan_logparser]#

conf is pointing to correct file

**Comment by v3gard** [comment]
Can you provide a sample of your log file please? Makes it easier to debug.
